services:
  # A Docker web service
  - type: web
    name: todos-service
    runtime: python
    plan: free
    autoDeploy: false
    buildCommand: pip install pipenv --user && pipenv install
    startCommand: pipenv run uvicorn main:app --host 0.0.0.0 --port 8080