from __future__ import annotations
from enum import StrEnum


class ErrorCode(StrEnum):
    TAG_NOT_FOUND = "TAG_NOT_FOUND"
    COMMENT_NOT_FOUND = "COMMENT_NOT_FOUND "
    USER_NOT_FOUND = "USER_NOT_FOUND"
    TODO_NOT_FOUND = "TODO_NOT_FOUND"
    TODO_CATEGORY_NOT_FOUND = "TODO_CATEGORY_NOT_FOUND"
    PROJECT_NOT_FOUND = "PROJECT_NOT_FOUND"
    INVALID_INPUT = "INVALID_INPUT"
    USER_ASSOCIATION_ALREADY_EXISTS = "USER_ASSOCIATION_ALREADY_EXISTS"
    TAG_PROJECT_ASSOCIATION_ALREADY_EXISTS = "TAG_PROJECT_ASSOCIATION_ALREADY_EXISTS"
    TAG_TODO_ASSOCIATION_ALREADY_EXISTS = "TAG_TODO_ASSOCIATION_ALREADY_EXISTS"
    CATEGORY_PROJECT_ASSOCIATION_ALREADY_EXISTS = (
        "CATEGORY_PROJECT_ASSOCIATION_ALREADY_EXISTS"
    )


class UserFriendlyError(Exception):
    def __init__(self, code: ErrorCode, description: str):
        self.code = code
        self.description = description
        super().__init__(description)
