export const TODO_ITEM_NEW_CATEGORY_DROP_ZONE_NAME =
	'TODO_ITEM_NEW_CATEGORY_DROP_ZONE_NAME' as const;
export const TODO_ITEM_ORDER_DROP_ZONE = 'TODO_ITEM_ORDER_DROP_ZONE' as const;
export const TODO_CATEGORY_ORDER_DROP_ZONE = 'TODO_CATEGORY_ORDER_DROP_ZONE' as const;
export const DROP_EVENT_HANDLED_BY_TODO_ITEM = 'DROP_EVENT_HANDLED_BY_TODO_ITEM' as const;
export const TODO_CATEGORIES_CONTEXT_NAME = 'TODO_CATEGORIES_CONTEXT_NAME' as const;
export const TODO_COMMENTS_STORE_NAME = 'TODO_COMMENTS_STORE_NAME' as const;
