export const TODO_ITEM_NEW_CATEGORY_DROP_ZONE_NAME =
	'TODO_ITEM_NEW_CATEGORY_DROP_ZONE_NAME' as const;
export const TODO_ITEM_ORDER_DROP_ZONE = 'TODO_ITEM_ORDER_DROP_ZONE' as const;
export const TODO_CATEGORY_ORDER_DROP_ZONE = 'TODO_CATEGORY_ORDER_DROP_ZONE' as const;
