name: CI
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_TEAM_ID }}

on:
  pull_request:
    branches:
      - master

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    environment: Preview – project-management-backend

    defaults:
      run:
        working-directory: ./backend

    env:
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_BACKEND_PROJECT_ID }}

    steps:
      - name: Find Deploy URLS Comment
        uses: peter-evans/find-comment@v3
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: "github-actions[bot]"
          body-includes: Deployment URLS (fohoov)

      - name: Create or Update Deploy URLs comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            Deployment URLS (fohoov)
            [<kbd> <br>Front<br> </kbd>][Link]

            [Link]: https://github.com/FoHoOV/project-management/pull/28#front
          edit-mode: replace

  deploy-frontend:
    runs-on: ubuntu-latest
    needs: deploy-backend
    environment: Preview – project-management-frontend

    defaults:
      run:
        working-directory: ./frontend

    env:
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_FRONTEND_PROJECT_ID }}

    steps:
      - name: Find Deploy URLS Comment
        uses: peter-evans/find-comment@v3
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: "github-actions[bot]"
          body-includes: Deployment URLS (fohoov)

      - name: Create or Update Deploy URLs comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            Deployment URLS (fohoov)
            [<kbd> <br>Back<br> </kbd>][Link]

            [Link]: https://github.com/FoHoOV/project-management/pull/28/#back
          edit-mode: append
