name: CI

on:
  pull_request:
    branches:
      - master

jobs:
  test-backend:
    name: Test Backend
    runs-on: ubuntu-latest
    env:
      ALLOWED_ORIGINS: '["http://localhost", "http://localhost:4173", "http://localhost:5173", "http://localhost:5174"]'
      IS_SQLALCHEMY_LOG_ENABLED: "True"
      SQLALCHEMY_DATABASE_URL: "sqlite:///./todos.db"
      SECRET_KEY: "21cc261d634e34ca74ea7a18b2db1f36423e42a1b047553af12cd40dc13b06ee"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          cd backend
          pip install -r requirements.txt

      - name: Run the backend tests
        run: |
          cd backend
          python3 -m pytest

      - name: Start backend service
        run: |
          cd backend
          python -m uvicorn main:app --host 0.0.0.0 --port 8080 &

  test-frontend:
    name: Test Frontend
    runs-on: ubuntu-latest
    needs: test-backend
    env:
      PUBLIC_API_URL: "http://127.0.0.1:8080"
      PUBLIC_API_REQUEST_TIMEOUT_MS: "10000"
      PUBLIC_COOKIES_EXPIRATION_SPAN_SECONDS: "5184000"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: |
          cd frontend
          npm install --legacy-peer-deps

      - name: Run frontend tests (with backend service running)
        run: |
          cd frontend
          npm run test
